---
- name: print_dns server
  hosts: all
  tasks:
    - shell: "echo {{hostvars['node01.host'].dns_server}} >> /tmp/variable.txt"

# inventory
#node00.host ansible_host=172.20.1.100 ansible_ssh_pass=Passw0rd ansible_user=root
#node01.host ansible_host=172.20.1.101 ansible_ssh_pass=Passw0rd ansible_user=root dns_server=8.8.8.8
